sudo: false

language: java

dist: trusty

jdk:
  - oraclejdk8
  #- openjdk8
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "jxsd1234a"
  - git config --local user.email "806521865@qq.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  # ⋮
env:
  global:
    - LAPIS_DEPLOY=https://github.com/LapisBlue/Deploy.git DEPLOY_ROOT=/tmp/lapis/deploy
    - secure: "zjPKbHmJf/XmRRdfsfCVSwXA0V6nzuqGwZeEi95UVTBuGANklLh47k2ChuX94E9sx9ZoaGcJoiruAEZ0Bke2iObLP/n1uzZvf+rWBBfkx4Q0D1s19hq7NraKUOWfvD+CC9b9MBfulYFaXek56udbE7HZsLQgOryogm4D68vg+oE="

after_success: ./etc/update_porekit

notifications:
  email: false
